version "2"

plugins:
  sonar-java:
    enabled: true
    config:
      sonar.java.source: 6
    checks:
      squid:S1845:
        enabled: false

exclude_patterns:
  - ".gradle/"
  - ".idea/"
  - "build/"
  - "bin/"
  - ".setting/"
